"""The database schema, expressed as SQLAlchemy ORM models.

Each class below maps to one Postgres table; each ``mapped_column`` maps to one
column. This is the single Python definition of FixMate's data model — the API
schemas (``fixmate/api/schemas.py``) and the SQL migrations
(``db/migrations/``) are kept in step with what is declared here.

Two rules run through almost every table:

  - **Tenant isolation:** every customer-owned table carries an
    ``organization_id`` foreign key (see ``_org_fk``). Row-Level Security
    policies key off this column so one tenant can never read another's rows
    (CLAUDE.md §6). The session machinery in ``fixmate/core/db.py`` supplies the
    current tenant.
  - **Auditability:** answers, fixes, and state changes are recorded immutably
    (``AnswerLog``, ``AuditEvent``) for legal defensibility and debugging
    (CLAUDE.md §8.2).

The small ``_uuid_pk`` / ``_org_fk`` / ``_created_at`` helpers exist only to
stamp out these repeated column definitions consistently.
"""

import uuid
from datetime import datetime

from pgvector.sqlalchemy import Vector
from sqlalchemy import (
    Boolean,
    CheckConstraint,
    Computed,
    ForeignKey,
    Integer,
    Text,
    text,
)
from sqlalchemy.dialects.postgresql import ARRAY, JSONB, TIMESTAMP, TSVECTOR, UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# BGE-M3 emits 1024-dim vectors; this dimension is a contract with the
# embeddings layer (Phase 2) and ingestion (Phase 3). Do not change without
# re-embedding every chunk.
EMBEDDING_DIM = 1024

# The lifecycle states a fix moves through; mirrored by the CHECK constraint on
# the fixes table and by the state machine in fixmate/curation/states.py.
FIX_STATES = ("submitted", "pending_review", "approved", "rejected", "unsafe", "retired")


class Base(DeclarativeBase):
    """SQLAlchemy declarative base; every model below inherits its metadata."""


def _uuid_pk() -> Mapped[uuid.UUID]:
    """Standard primary key: a UUID generated by Postgres (``gen_random_uuid()``)."""
    return mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )


def _org_fk() -> Mapped[uuid.UUID]:
    """The ``organization_id`` tenant key present on every customer-owned table.

    Indexed (queries always filter by tenant) and ``ON DELETE CASCADE`` so
    deleting an organization cleanly removes all of its data.
    """
    return mapped_column(
        UUID(as_uuid=True),
        ForeignKey("organizations.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )


def _created_at() -> Mapped[datetime]:
    """A timezone-aware creation timestamp defaulted to ``now()`` by Postgres."""
    return mapped_column(TIMESTAMP(timezone=True), nullable=False, server_default=text("now()"))


class Organization(Base):
    """A customer tenant. The root of the isolation hierarchy: every other
    customer-owned row points back here via ``organization_id``."""

    __tablename__ = "organizations"

    id: Mapped[uuid.UUID] = _uuid_pk()
    name: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = _created_at()


class User(Base):
    """A person within one organization. ``role`` is one of ``tech`` (field
    technician), ``curator`` (reviews/approves fixes), or ``admin`` (manages
    users and everything a curator can do) — enforced by a CHECK constraint and
    used for API access control in ``fixmate/api/deps.py``."""

    __tablename__ = "users"
    __table_args__ = (
        CheckConstraint("role IN ('tech', 'curator', 'admin')", name="users_role_check"),
    )

    id: Mapped[uuid.UUID] = _uuid_pk()
    organization_id: Mapped[uuid.UUID] = _org_fk()
    email: Mapped[str | None] = mapped_column(Text)
    name: Mapped[str] = mapped_column(Text, nullable=False)
    role: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = _created_at()


class EquipmentProfile(Base):
    """A piece of equipment a technician troubleshoots (e.g. "Pump X"). Manuals,
    fixes, and conversations are scoped to an equipment profile so retrieval only
    searches material relevant to the machine in front of the technician."""

    __tablename__ = "equipment_profiles"

    id: Mapped[uuid.UUID] = _uuid_pk()
    organization_id: Mapped[uuid.UUID] = _org_fk()
    name: Mapped[str] = mapped_column(Text, nullable=False)
    manufacturer: Mapped[str | None] = mapped_column(Text)
    model: Mapped[str | None] = mapped_column(Text)
    created_at: Mapped[datetime] = _created_at()


class Document(Base):
    """An uploaded manual (one PDF) for a piece of equipment.

    Documents are versioned rather than overwritten: uploading a new revision
    creates a new row and points the old one's ``superseded_by`` at it. Retrieval
    excludes superseded documents so answers never cite outdated procedures
    (CLAUDE.md §10). ``storage_key`` references the original PDF in object
    storage; the extracted text lives in ``Chunk`` rows."""

    __tablename__ = "documents"

    id: Mapped[uuid.UUID] = _uuid_pk()
    organization_id: Mapped[uuid.UUID] = _org_fk()
    equipment_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("equipment_profiles.id", ondelete="CASCADE"), nullable=False
    )
    title: Mapped[str] = mapped_column(Text, nullable=False)
    version: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("1"))
    superseded_by: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("documents.id", ondelete="SET NULL")
    )
    storage_key: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = _created_at()


class Conversation(Base):
    """A troubleshooting session between one user and the assistant, optionally
    pinned to a piece of equipment. Groups the back-and-forth ``Message`` rows so
    follow-up questions have multi-turn context."""

    __tablename__ = "conversations"

    id: Mapped[uuid.UUID] = _uuid_pk()
    organization_id: Mapped[uuid.UUID] = _org_fk()
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    equipment_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("equipment_profiles.id", ondelete="SET NULL")
    )
    created_at: Mapped[datetime] = _created_at()


class AnswerLog(Base):
    """The immutable audit record of one generated answer (CLAUDE.md §8.2).

    Every answer the system produces is logged here with *exactly* what went into
    and came out of it: the question, the final answer text, the ids of the
    retrieved chunks (``retrieved_chunk_ids``), which model/provider generated it,
    the confidence band, the citations, the groundedness-check result, and the
    token count. This enables "why did it say that?" investigations, regression
    testing, and legal defensibility. Records are written once and never updated.
    """

    __tablename__ = "answer_logs"

    id: Mapped[uuid.UUID] = _uuid_pk()
    organization_id: Mapped[uuid.UUID] = _org_fk()
    conversation_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("conversations.id", ondelete="SET NULL")
    )
    question: Mapped[str] = mapped_column(Text, nullable=False)
    answer_text: Mapped[str] = mapped_column(Text, nullable=False)
    retrieved_chunk_ids: Mapped[list[uuid.UUID]] = mapped_column(
        ARRAY(UUID(as_uuid=True)), nullable=False, server_default=text("'{}'")
    )
    model_version: Mapped[str] = mapped_column(Text, nullable=False)
    provider: Mapped[str] = mapped_column(Text, nullable=False)
    confidence: Mapped[str] = mapped_column(Text, nullable=False)
    citations: Mapped[dict | list | None] = mapped_column(JSONB)
    groundedness: Mapped[dict | None] = mapped_column(JSONB)
    tokens_used: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("0"))
    created_at: Mapped[datetime] = _created_at()


class Message(Base):
    """One turn in a conversation. ``role`` is ``user`` (the technician's
    question) or ``assistant`` (the generated reply). Assistant messages link to
    the ``AnswerLog`` that produced them via ``answer_log_id``, tying the
    user-facing transcript to the full audit record."""

    __tablename__ = "messages"
    __table_args__ = (CheckConstraint("role IN ('user', 'assistant')", name="messages_role_check"),)

    id: Mapped[uuid.UUID] = _uuid_pk()
    organization_id: Mapped[uuid.UUID] = _org_fk()
    conversation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("conversations.id", ondelete="CASCADE"), nullable=False
    )
    role: Mapped[str] = mapped_column(Text, nullable=False)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    answer_log_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("answer_logs.id", ondelete="SET NULL")
    )
    created_at: Mapped[datetime] = _created_at()


class Fix(Base):
    """A field-verified repair tip — the heart of FixMate's competitive moat.

    A fix starts life as a technician's suggestion (``submitted``) and moves
    through human review (``pending_review`` -> ``approved`` / ``rejected`` /
    ``unsafe`` -> ``retired``); see ``FIX_STATES`` and
    ``fixmate/curation/states.py``. Only ``approved`` fixes are indexed as
    searchable ``Chunk`` rows and surfaced to technicians, always with a
    verification badge. ``ai_prescreen_report`` stores the AI safety advisory
    shown to the human curator (the AI assists; humans approve — CLAUDE.md §2.5).
    """

    __tablename__ = "fixes"
    __table_args__ = (
        CheckConstraint(
            "state IN ('submitted', 'pending_review', 'approved', 'rejected', 'unsafe', 'retired')",
            name="fixes_state_check",
        ),
    )

    id: Mapped[uuid.UUID] = _uuid_pk()
    organization_id: Mapped[uuid.UUID] = _org_fk()
    equipment_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("equipment_profiles.id", ondelete="CASCADE"), nullable=False
    )
    question_text: Mapped[str | None] = mapped_column(Text)
    answer_log_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("answer_logs.id", ondelete="SET NULL")
    )
    proposed_text: Mapped[str] = mapped_column(Text, nullable=False)
    photos: Mapped[list | None] = mapped_column(JSONB)
    submitted_by: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    state: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'submitted'"))
    reviewed_by: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL")
    )
    review_notes: Mapped[str | None] = mapped_column(Text)
    ai_prescreen_report: Mapped[dict | None] = mapped_column(JSONB)
    approved_at: Mapped[datetime | None] = mapped_column(TIMESTAMP(timezone=True))
    version: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("1"))
    created_at: Mapped[datetime] = _created_at()
    updated_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, server_default=text("now()")
    )


class Chunk(Base):
    """A searchable unit of knowledge — the atoms retrieval works over.

    A chunk is either a slice of a manual (``source_type='manual'``, linked to a
    ``Document``) or an approved field fix (``source_type='field_fix'``, linked to
    a ``Fix``). Each chunk carries two search representations side by side, which
    is what makes retrieval *hybrid*:

      - ``embedding``: a 1024-dim dense vector (see ``EMBEDDING_DIM``) for
        semantic / meaning-based similarity search via pgvector.
      - ``tsv``: a Postgres full-text-search vector, auto-computed from
        ``content``, for exact keyword matches (error codes, part numbers).

    ``positive_signals`` accumulates "this helped" feedback for future ranking
    boosts (FR-13)."""

    __tablename__ = "chunks"
    __table_args__ = (
        CheckConstraint("source_type IN ('manual', 'field_fix')", name="chunks_source_type_check"),
    )

    id: Mapped[uuid.UUID] = _uuid_pk()
    organization_id: Mapped[uuid.UUID] = _org_fk()
    document_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("documents.id", ondelete="CASCADE")
    )
    source_type: Mapped[str] = mapped_column(Text, nullable=False)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    page: Mapped[int | None] = mapped_column(Integer)
    fix_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("fixes.id", ondelete="CASCADE")
    )
    # Reinforcement signal (FR-13): incremented when a technician marks an answer
    # that cited this chunk as helpful. Stored now; consumed by ranking later.
    positive_signals: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default=text("0")
    )
    embedding: Mapped[list[float]] = mapped_column(Vector(EMBEDDING_DIM), nullable=False)
    # 'english' config gives stemming ("valves" matches "valve"); if more launch
    # languages are added later (FR-7), switch to 'simple' or per-language configs.
    tsv: Mapped[str] = mapped_column(
        TSVECTOR, Computed("to_tsvector('english', content)", persisted=True)
    )
    created_at: Mapped[datetime] = _created_at()


class Figure(Base):
    """A diagram/photo extracted from a manual page during ingestion.

    The image bytes live in object storage (``storage_key``); ``bbox`` records
    where on the page it was found and ``caption`` is the AI-generated
    description that gets indexed so figures are retrievable by what they show.
    At answer time, relevant figures are embedded into the steps that reference
    them (CLAUDE.md §2.3)."""

    __tablename__ = "figures"

    id: Mapped[uuid.UUID] = _uuid_pk()
    organization_id: Mapped[uuid.UUID] = _org_fk()
    document_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("documents.id", ondelete="CASCADE"), nullable=False
    )
    page: Mapped[int] = mapped_column(Integer, nullable=False)
    caption: Mapped[str | None] = mapped_column(Text)
    storage_key: Mapped[str] = mapped_column(Text, nullable=False)
    bbox: Mapped[dict | None] = mapped_column(JSONB)
    created_at: Mapped[datetime] = _created_at()


class Feedback(Base):
    """A technician's "did it help?" verdict on one assistant message.

    ``helped`` captures the thumbs up/down. A "not helped" response can spawn a
    candidate ``Fix`` (linked via ``fix_id``), feeding the curation loop; a
    "helped" response reinforces the cited chunks (FR-12/FR-13). See
    ``fixmate/feedback/service.py``."""

    __tablename__ = "feedback"

    id: Mapped[uuid.UUID] = _uuid_pk()
    organization_id: Mapped[uuid.UUID] = _org_fk()
    message_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("messages.id", ondelete="CASCADE"), nullable=False
    )
    user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL")
    )
    helped: Mapped[bool] = mapped_column(Boolean, nullable=False)
    fix_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("fixes.id", ondelete="SET NULL")
    )
    created_at: Mapped[datetime] = _created_at()


class AuditEvent(Base):
    """An immutable record of one state-changing action (CLAUDE.md §8.2).

    Whenever a fix changes state, a user is created/modified, equipment is
    edited, etc., a row is appended here capturing *who* (``actor_id``) did
    *what* (``action``) to *which* entity (``entity_type``/``entity_id``), plus
    JSON snapshots of the row ``before`` and ``after``. ``actor_id`` is a plain
    UUID with no foreign key on purpose: audit rows must outlive the users they
    reference (24-month retention)."""

    __tablename__ = "audit_events"

    id: Mapped[uuid.UUID] = _uuid_pk()
    organization_id: Mapped[uuid.UUID] = _org_fk()
    # Plain UUID (no FK): audit rows must survive actor deletion (24-month retention).
    actor_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True))
    entity_type: Mapped[str] = mapped_column(Text, nullable=False)
    entity_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    action: Mapped[str] = mapped_column(Text, nullable=False)
    before: Mapped[dict | None] = mapped_column(JSONB)
    after: Mapped[dict | None] = mapped_column(JSONB)
    created_at: Mapped[datetime] = _created_at()
